apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: port-k8s-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://port-labs.github.io/helm-charts
    chart: port-k8s-exporter
    targetRevision: 0.3.19
    helm:
      values: |
        secret:
          useExistingSecret: true
          name: port-credentials
        overwriteConfigurationOnRestart: true
        stateKey: kind-dot
        extraEnv:
          - name: CLUSTER_NAME
            value: kind-dot
        configMap:
          config:
            resources:
              # Cluster
              - kind: v1/namespaces
                selector:
                  query: .metadata.name | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: '(.metadata.name) + "-" + env.CLUSTER_NAME'
                        title: .metadata.name
                        blueprint: '"namespace"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          labels: .metadata.labels
                        relations:
                          Cluster: env.CLUSTER_NAME
              # Workloads (Deployments)
              - kind: apps/v1/deployments
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-Deployment-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        icon: '"Deployment"'
                        blueprint: '"workload"'
                        properties:
                          kind: '"Deployment"'
                          creationTimestamp: .metadata.creationTimestamp
                          replicas: .spec.replicas
                          hasPrivileged: .spec.template.spec.containers | [.[].securityContext.privileged] | any
                          hasLatest: .spec.template.spec.containers[].image | contains(":latest")
                          hasLimits: .spec.template.spec.containers | all(has("resources") and (.resources.limits.memory and .resources.limits.cpu))
                          strategyConfig: .spec.strategy
                          strategy: .spec.strategy.type
                          availableReplicas: .status.availableReplicas
                          labels: .metadata.labels
                          containers: (.spec.template.spec.containers | map({name, image, resources}))
                          isHealthy: if .spec.replicas == .status.availableReplicas then "Healthy" else "Unhealthy" end
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Workloads (DaemonSets)
              - kind: apps/v1/daemonsets
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-DaemonSet-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        icon: '"Deployment"'
                        blueprint: '"workload"'
                        properties:
                          kind: '"DaemonSet"'
                          creationTimestamp: .metadata.creationTimestamp
                          replicas: .spec.replicas
                          strategyConfig: .spec.strategy
                          availableReplicas: .status.availableReplicas
                          hasPrivileged: .spec.template.spec.containers | [.[].securityContext.privileged] | any
                          labels: .metadata.labels
                          hasLatest: .spec.template.spec.containers[].image | contains(":latest")
                          hasLimits: .spec.template.spec.containers | all(has("resources") and (.resources.limits.memory and .resources.limits.cpu))
                          containers: (.spec.template.spec.containers | map({name, image, resources}))
                          isHealthy: if .status.desiredNumberScheduled == .status.currentNumberScheduled then "Healthy" else "Unhealthy" end
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Workloads (StatefulSets)
              - kind: apps/v1/statefulsets
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-StatefulSet-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        icon: '"Deployment"'
                        blueprint: '"workload"'
                        properties:
                          kind: '"StatefulSet"'
                          creationTimestamp: .metadata.creationTimestamp
                          replicas: .spec.replicas
                          strategyConfig: .spec.strategy
                          availableReplicas: .status.availableReplicas
                          hasPrivileged: .spec.template.spec.containers | [.[].securityContext.privileged] | any
                          labels: .metadata.labels
                          hasLatest: .spec.template.spec.containers[].image | contains(":latest")
                          hasLimits: .spec.template.spec.containers | all(has("resources") and (.resources.limits.memory and .resources.limits.cpu))
                          containers: (.spec.template.spec.containers | map({name, image, resources}))
                          isHealthy: if .spec.replicas == .status.availableReplicas then "Healthy" else "Unhealthy" end
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Apps CRD
              - kind: devopstoolkit.live/v1beta1/apps
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"app"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          image: .spec.image
                          tag: .spec.tag
                          port: .spec.port
                          host: .spec.host
                          scalingEnabled: .spec.scaling.enabled
                          scalingMin: .spec.scaling.min
                          scalingMax: .spec.scaling.max
                          composition: .spec.crossplane.compositionSelector.matchLabels.type + "-" + .spec.crossplane.compositionSelector.matchLabels.location
                          synced: .status.conditions[] | select(.type == "Synced") | .status
                          ready: .status.conditions[] | select(.type == "Ready") | .status
                          labels: .metadata.labels
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # SQLs CRD
              - kind: devopstoolkit.live/v1beta1/sqls
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"sql"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          version: .spec.version
                          size: .spec.size
                          region: .spec.region
                          databases: .spec.databases
                          provider: .spec.crossplane.compositionSelector.matchLabels.provider
                          dbType: .spec.crossplane.compositionSelector.matchLabels.db
                          synced: .status.conditions[] | select(.type == "Synced") | .status
                          ready: .status.conditions[] | select(.type == "Ready") | .status
                          labels: .metadata.labels
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
  destination:
    server: https://kubernetes.default.svc
    namespace: port-k8s-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
